/*
 * Copyright (c) 2021 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include "led_state_event.h"

char *get_led_state_type_str(enum led_state type)
{
	switch (type) {
		case LED_STATE_BATTERY_FULL:
			return "LED_STATE_BATTERY_FULL";
		case LED_STATE_BATTERY_MED:
			return "LED_STATE_BATTERY_MED";
		case LED_STATE_BATTERY_EMPTY:
			return "LED_STATE_BATTERY_EMPTY";
		case LED_STATE_CHARGE_BATTERY_FULL:
			return "LED_STATE_CHARGE_BATTERY_FULL";
		case LED_STATE_CHARGE_BATTERY_IN_CHARING:
			return "LED_STATE_CHARGE_BATTERY_IN_CHARING";
		case LED_STATE_CHARGE_BATTERY_ERROR:
			return "LED_STATE_CHARGE_BATTERY_ERROR";
		case LED_STATE_SENSOR_AQUIRING:
			return "LED_STATE_SENSOR_AQUIRING";
		case LED_STATE_LORA_LISTEN:
			return "LED_STATE_LORA_LISTEN";
		case LED_STATE_LORA_SEND:
			return "LED_STATE_LORA_SEND";
		case LED_STATE_LORA_NACK:
			return "LED_STATE_LORA_NACK";
		case LED_STATE_LORA_ERROR:
			return "LED_STATE_LORA_ERROR";
		case LED_STATE_LTE_DISCONNECTED:
			return "LED_STATE_LTE_DISCONNECTED";
		case LED_STATE_LTE_CONNECTING:
			return "LED_STATE_LTE_CONNECTING";
		case LED_STATE_LTE_CONNECTED:
			return "LED_STATE_LTE_CONNECTED";
		case LED_STATE_LTE_ERROR:
			return "LED_STATE_LTE_ERROR";
		case LED_STATE_CLOUD_DISCONNECTED:
			return "LED_STATE_CLOUD_DISCONNECTED";
		case LED_STATE_CLOUD_CONNECTING:
			return "LED_STATE_CLOUD_CONNECTING";
		case LED_STATE_CLOUD_CONNECTED:
			return "LED_STATE_CLOUD_CONNECTED";
		case LED_STATE_CLOUD_ERROR:
			return "LED_STATE_CLOUD_ERROR";
		case LED_STATE_FOTA_DOWNLOADING:
			return "LED_STATE_FOTA_DOWNLOADING";
		case LED_STATE_FOTA_INSTALLING:
			return "LED_STATE_FOTA_INSTALLING";
		case LED_STATE_FOTA_ERROR:
			return "LED_STATE_FOTA_ERROR";
		case LED_STATE_UNKNOWN_ERROR:
			return "LED_STATE_UNKNOWN_ERROR";
		case LED_STATE_MODEM_RECOVERABLE_ERROR:
			return "LED_STATE_MODEM_RECOVERABLE_ERROR";
		case LED_STATE_MODEM_IRRECOVERABLE_ERROR:
			return "LED_STATE_MODEM_IRRECOVERABLE_ERROR";
		case LED_STATE_FUNCTIONAL_TEST_IN_PROGRESS:
			return "LED_STATE_FUNCTIONAL_TEST_IN_PROGRESS";
		case LED_STATE_FUNCTIONAL_TEST_PASS:
			return "LED_STATE_FUNCTIONAL_TEST_PASS";
		case LED_STATE_FUNCTIONAL_TEST_FAIL:
			return "LED_STATE_FUNCTIONAL_TEST_FAIL";
		case LED_STATE_CALIBRATION_IN_PROCESS:
			return "LED_STATE_CALIBRATION_IN_PROCESS";
		case LED_STATE_CALIBRATION_SUCCESS:
			return "LED_STATE_CALIBRATION_SUCCESS";
		case LED_STATE_CALIBRATION_AMBIENT_FAIL:
			return "LED_STATE_CALIBRATION_AMBIENT_FAIL";
		case LED_STATE_CALIBRATION_MEASUREMENT_FAIL:
			return "LED_STATE_CALIBRATION_MEASUREMENT_FAIL";
		case LED_STATE_TURN_OFF:
			return "LED_STATE_TURN_OFF";
		default:
			return "Unknown LED State";
	}
}

APP_EVENT_TYPE_DEFINE(led_state_event,
		  NULL,
		  NULL,
		  APP_EVENT_FLAGS_CREATE(APP_EVENT_TYPE_FLAGS_INIT_LOG_ENABLE));
