#ifndef _LED_STATE_EVENT_H_
#define _LED_STATE_EVENT_H_

#include <app_event_manager.h>
#include <app_event_manager_profiler_tracer.h>


/** @brief Asset Tracker led states in the application. */
enum led_state {
	LED_STATE_BATTERY_FULL,
	LED_STATE_BATTERY_MED,
	LED_STATE_BATTERY_EMPTY,
	LED_STATE_CHARGE_BATTERY_FULL,
	LED_STATE_CHARGE_BATTERY_IN_CHARING,
	LED_STATE_CHARGE_BATTERY_ERROR,
	LED_STATE_SENSOR_AQUIRING,
	LED_STATE_LORA_LISTEN,
	LED_STATE_LORA_SEND,
	LED_STATE_LORA_NACK,
	LED_STATE_LORA_ERROR,
	LED_STATE_LTE_DISCONNECTED,
	LED_STATE_LTE_CONNECTING,
	LED_STATE_LTE_CONNECTED,
	LED_STATE_LTE_ERROR,
	LED_STATE_CLOUD_DISCONNECTED,
	LED_STATE_CLOUD_CONNECTING,
	LED_STATE_CLOUD_CONNECTED,
	LED_STATE_CLOUD_ERROR,
	LED_STATE_FOTA_DOWNLOADING,
	LED_STATE_FOTA_INSTALLING,
	LED_STATE_FOTA_ERROR,
	LED_STATE_UNKNOWN_ERROR,
	LED_STATE_MODEM_RECOVERABLE_ERROR,
	LED_STATE_MODEM_IRRECOVERABLE_ERROR,
	LED_STATE_FUNCTIONAL_TEST_IN_PROGRESS,
	LED_STATE_FUNCTIONAL_TEST_PASS,
	LED_STATE_FUNCTIONAL_TEST_FAIL,
	LED_STATE_CALIBRATION_IN_PROCESS,
	LED_STATE_CALIBRATION_SUCCESS,
	LED_STATE_CALIBRATION_AMBIENT_FAIL,
	LED_STATE_CALIBRATION_MEASUREMENT_FAIL,
	LED_STATE_CALIBRATION_TIMEOUT,
	LED_STATE_TURN_OFF,
	LED_STATE_COUNT
};

/** @brief Led state event. */
struct led_state_event {
	struct app_event_header header; /**< Event header. */

	enum led_state state;
};

APP_EVENT_TYPE_DECLARE(led_state_event);

char *get_led_state_type_str(enum led_state type);
/** @} */

#endif /* _LED_STATE_EVENT_H_ */
