# Additional resources for Zephyr CI:
## https://gitlab.com/zygoon/zephyr-ci-pipelines
## https://github.com/circuitdojo/nrf9160-feather-examples-and-drivers/blob/v1.7.x/.github/workflows/build.yml
## https://github.com/zephyrproject-rtos/zephyr/tree/main/.github/workflows

image: ghcr.io/zephyrproject-rtos/ci:v0.24.6

clone:
  depth: 1

# definitions:
#   caches:
#     zephyr: ../monitor/

pipelines:
  pull-requests:
    '**':
      - step:
          name: 'Setup'
          # ToDo: add caching for Zephyr modules, so they don't need
          # to be downloaded every time.
          # caches:
          #   - zephyr
          script:
            - export BITBUCKET_COMMIT_SHORT="${BITBUCKET_COMMIT::7}"
            - git config --global user.email "you@example.com"
            - git config --global user.name "Your Name"
            - west init -l .
            - west update
            # Apply patches
            - ./scripts/apply_patches.sh
            - mkdir -p .out/update
            - west build -b etc_v0_2 -s applications/etc-app -p
            - cp build/zephyr/merged.hex ".out/monitor2.0_etc_v0_2_vX.X.X_${BITBUCKET_COMMIT_SHORT}.hex"
            - cp build/zephyr/app_update.bin ".out/update/update_monitor2.0_etc_v0_2_vX.X.X_${BITBUCKET_COMMIT_SHORT}.bin"
            - west build -b etc_v0_2 -s applications/etc-app -p -- -DOVERLAY_CONFIG="debug.conf rtt.conf"
            - cp build/zephyr/merged.hex ".out/monitor2.0_etc_v0_2_vX.X.X_${BITBUCKET_COMMIT_SHORT}_debug.hex"
            - cp build/zephyr/app_update.bin ".out/update/update_monitor2.0_etc_v0_2_vX.X.X_${BITBUCKET_COMMIT_SHORT}_debug.bin"
          artifacts:
            - .out/**

  custom:
    clear-cache:
      - step:
          image: atlassian/default-image:latest
          script:
            - pipe: atlassian/bitbucket-clear-cache:3.2.0
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD



