manifest:
  self:
    path: etc-firmware

  remotes:
    - name: sdk-nrf
      url-base: https://github.com/nrfconnect
    - name: exact
      url-base: https://github.com/exact-technology
    - name: exact-ssh
      url-base: git@github.com:exact-technology

  projects:
    - name: nrf
      remote: sdk-nrf
      repo-path: sdk-nrf
      revision: v2.7.0
      import: true
    # list the Memfault SDK as a top-level module
    - name: memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: 1.4.2
    - name: segger
      revision: globals_typedef
      path: modules/debug/segger
      remote: exact
    - name: etc-common-firmware
      remote: exact-ssh
      revision: 61ff6ce793ab8e26a0e01fa370c9224e758963f2
      path: modules/exact
