manifest:
  self:
    path: etc-firmware

  remotes:
    - name: sdk-nrf
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: sdk-nrf
      repo-path: sdk-nrf
      revision: v2.4.2
      import: true
    # list the Memfault SDK as a top-level module
    - name: memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: 1.4.2
    
