# AWS IoT library
CONFIG_AWS_IOT=y
CONFIG_AWS_IOT_CLIENT_ID_APP=y
CONFIG_AWS_IOT_BROKER_HOST_NAME="a3mld5b8glqv1c-ats.iot.us-west-2.amazonaws.com"
CONFIG_AWS_IOT_PORT=8883
CONFIG_AWS_IOT_SEC_TAG=201
CONFIG_AWS_IOT_APP_SUBSCRIPTION_LIST_COUNT=1
CONFIG_AWS_IOT_TOPIC_UPDATE_DELTA_SUBSCRIBE=n
CONFIG_AWS_IOT_LAST_WILL=n
CONFIG_AWS_IOT_TOPIC_GET_ACCEPTED_SUBSCRIBE=n
CONFIG_AWS_IOT_TOPIC_GET_REJECTED_SUBSCRIBE=n
CONFIG_AWS_IOT_MQTT_RX_TX_BUFFER_LEN=512
CONFIG_AWS_IOT_MQTT_PAYLOAD_BUFFER_LEN=512
CONFIG_AWS_IOT_CONNECTION_POLL_THREAD=y
CONFIG_AWS_IOT_PROVISION_CERTIFICATES=y

# MQTT - Maximum MQTT keepalive timeout specified by AWS IoT Core
CONFIG_MQTT_KEEPALIVE=15
CONFIG_MQTT_CLEAN_SESSION=y

# MQTT TLS
CONFIG_MQTT_LIB_TLS=y

CONFIG_ZCBOR=y
CONFIG_ZCBOR_CANONICAL=y
CONFIG_MGMT_MAX_DECODING_LEVELS=5