### Cloud/Modem log levels ###
CONFIG_MODEM_LOG_LEVEL_DBG=y
# CONFIG_MODEM_LOG_LEVEL_INF=y
# CONFIG_MODEM_CONTEXT_VERBOSE_DEBUG=y
CONFIG_LWM2M_LOG_LEVEL_DBG=y
CONFIG_CLOUD_CODEC_LOG_LEVEL_DBG=y
CONFIG_CLOUD_INTEGRATION_LOG_LEVEL_DBG=y

### UART/Shell/Console log levels ###
# CONFIG_MCUMGR_SMP_LOG_LEVEL_DBG=y
# CONFIG_MCUMGR_LOG_LEVEL_DBG=y
# CONFIG_UART_LOG_LEVEL_DBG=y

### Net log levels ###
# CONFIG_NET_CORE_LOG_LEVEL_DBG=y
# CONFIG_NET_IF_LOG_LEVEL_DBG=y
# CONFIG_NET_CONN_LOG_LEVEL_DBG=y
# CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=y
# CONFIG_NET_ROUTE_LOG_LEVEL_DBG=y
# CONFIG_NET_IPV4_LOG_LEVEL_DBG=y

### Peripheral devices log levels ###
# CONFIG_I2C_SHELL=y
CONFIG_BQ25618_LOG_LEVEL_DBG=y

### ETC APP log levels ###
CONFIG_ETC_APP_LOG_LEVEL_DBG=y
CONFIG_ETC_SETTINGS_LOG_LEVEL_DBG=y
# CONFIG_LORA_LOG_LEVEL_DBG=y

### Date/Time and RTC log levels ###
CONFIG_WATCHDOG_LOG_LEVEL_DBG=y
CONFIG_DATE_TIME_LOG_LEVEL_DBG=y
CONFIG_PCF85263_LOG_LEVEL_DBG=n

### ETC Libs log levels ###
CONFIG_UI_LOG_LEVEL_DBG=y
CONFIG_ETC_INTERFACE_LOG_LEVEL_DBG=y

### Memory log levels ###
CONFIG_STREAM_FLASH_LOG_LEVEL_DBG=y
CONFIG_FLASH_LOG_LEVEL_DBG=y
