# General config
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_ASSERT=y
CONFIG_REBOOT=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_FPU=y
CONFIG_FW_INFO=y

# Heap and stacks
CONFIG_HW_STACK_PROTECTION=y

# Flash Settings
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_SOC_FLASH_NRF_UICR=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

# Application Event Manager
CONFIG_APP_EVENT_MANAGER=y
CONFIG_APP_EVENT_MANAGER_LOG_EVENT_TYPE=n

# Enable uart console
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_UART_LINE_CTRL=y

CONFIG_MCUBOOT_IMAGE_VERSION="1.0.3+0"

# Enable ETC setting for system configuration
CONFIG_ETC_SETTINGS=y

# Enable Date Time customize with BG95
CONFIG_ETC_DATE_TIME=y

# Device Mode
CONFIG_ETC_DEVICE=y
CONFIG_ETC_DEVICE_MODE=2

############ LwM2M Configuration ############
# DTLS Configuration for use with Quectel BG95
CONFIG_MODEM_QUECTEL_BG95_M3_PSK_KEY="70475440693636213646256D7744"

# ETC Device configuration
CONFIG_ETC_DEVICE_MODE=2
CONFIG_ETC_DEVICE_RADIO_MODE=0

CONFIG_LOG_BUFFER_SIZE=2048

# LwM2M Server configuration
CONFIG_LWM2M_INTEGRATION_SERVER_URL="coaps://us.iot.avsystem.cloud:5684"
CONFIG_LWM2M_RD_CLIENT_SUPPORT_BOOTSTRAP=n

# General LwM2M config
CONFIG_EXACT_LWM2M_CLIENT_UTILS=y
CONFIG_EXACT_LWM2M_CLIENT_UTILS_SECURITY_OBJ_SUPPORT=y
CONFIG_LWM2M_INTEGRATION=y
CONFIG_LWM2M=y
CONFIG_LWM2M_DTLS_SUPPORT=y
CONFIG_LWM2M_SECURITY_KEY_SIZE=33
CONFIG_LWM2M_VERSION_1_1=y
CONFIG_LWM2M_ENGINE_STACK_SIZE=4096
CONFIG_LWM2M_COAP_BLOCK_SIZE=1024
CONFIG_LWM2M_DNS_SUPPORT=y
CONFIG_LWM2M_SECURITY_INSTANCE_COUNT=2
CONFIG_COAP_INIT_ACK_TIMEOUT_MS=4000
CONFIG_BASE64=y

# Transmission buffers.
CONFIG_LWM2M_ENGINE_MAX_OBSERVER=5
CONFIG_LWM2M_ENGINE_MAX_MESSAGES=5
CONFIG_LWM2M_ENGINE_MAX_REPLIES=2
CONFIG_LWM2M_ENGINE_MAX_PENDING=2

# CBOR encoding.
CONFIG_LWM2M_RW_SENML_CBOR_SUPPORT=y
CONFIG_LWM2M_RW_SENML_CBOR_RECORDS=65
CONFIG_ZCBOR=y
CONFIG_ZCBOR_CANONICAL=y
CONFIG_MGMT_MAX_DECODING_LEVELS=5

# Set uptime to once every 12 hours.
CONFIG_LWM2M_ENGINE_DEFAULT_LIFETIME=43200

# LwM2M Queue Mode
CONFIG_LWM2M_QUEUE_MODE_ENABLED=y
CONFIG_LWM2M_RD_CLIENT_SUSPEND_SOCKET_AT_IDLE=n
# Sets the duration that the lwm2m engine will be polling for data after transmission before
# the socket is closed.
CONFIG_LWM2M_QUEUE_MODE_UPTIME=30

# Adjust this to match the longest possible list size in the application.
# Should be minimum the maximum number of supported objects that can be sent simultaneously.
CONFIG_LWM2M_COMPOSITE_PATH_LIST_SIZE=15

# Enable CoAP extended option length.
CONFIG_COAP_EXTENDED_OPTIONS_LEN=y
CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE=40

## Zephyr LwM2M Objects
# IPSO v1.1
CONFIG_LWM2M_IPSO_SUPPORT=y

# IPSO Temperature
# Use EXACT Temperature sensor object instead of IPSO
CONFIG_LWM2M_IPSO_TEMP_SENSOR=n

# IPSO Humidity
CONFIG_LWM2M_IPSO_HUMIDITY_SENSOR=y
CONFIG_LWM2M_IPSO_HUMIDITY_SENSOR_VERSION_1_1=y

# Connectivity Monitoring Object
CONFIG_LWM2M_CONNMON_OBJECT_VERSION_1_2=y
CONFIG_LWM2M_CONN_MON_OBJ_SUPPORT=y
CONFIG_LWM2M_CONN_MON_BEARER_MAX=1

# FOTA
CONFIG_FOTA_DOWNLOAD=y
CONFIG_DFU_TARGET=y
CONFIG_DOWNLOAD_CLIENT=y
CONFIG_DOWNLOAD_CLIENT_HTTP_FRAG_SIZE_1024=y
CONFIG_DOWNLOAD_CLIENT_STACK_SIZE=4096
CONFIG_DOWNLOAD_CLIENT_BUF_SIZE=1500
CONFIG_DOWNLOAD_CLIENT_MAX_HOSTNAME_SIZE=128
