# General config
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_ASSERT=y
CONFIG_REBOOT=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_FPU=y
CONFIG_FW_INFO=y

# Heap and stacks
CONFIG_HW_STACK_PROTECTION=y

# Flash Settings
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_SOC_FLASH_NRF_UICR=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_STREAM_FLASH_LOG_LEVEL_DBG=y

# Application Event Manager
CONFIG_APP_EVENT_MANAGER=y
CONFIG_APP_EVENT_MANAGER_LOG_EVENT_TYPE=n
CONFIG_ETC_APP_LOG_LEVEL_DBG=y

# Enable uart console
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_UART_LINE_CTRL=y

CONFIG_WATCHDOG_LOG_LEVEL_DBG=y
CONFIG_DATA_FS_LOG_LEVEL_DBG=y
CONFIG_DATE_TIME_LOG_LEVEL_DBG=y
CONFIG_PCF85263_LOG_LEVEL_DBG=n

CONFIG_MCUBOOT_IMAGE_VERSION="1.0.3+0"

# Enable ETC setting for system configuration
CONFIG_ETC_SETTINGS=y

# Enable Date Time customize with BG95
CONFIG_ETC_DATE_TIME=y

# Device Mode
CONFIG_ETC_DEVICE=y
CONFIG_ETC_DEVICE_MODE=2