/* 
 * Copyright (c) 2023 EXACT Technology
 */

#ifndef CONFIGURATION_OBJECT_H__
#define CONFIGURATION_OBJECT_H__

/* Configuration object resource IDs */
#define ETC_CFG_OBJ_R_DEVICE_MODE		1U
#define ETC_CFG_OBJ_R_POWER_MODE		2U
#define ETC_CFG_OBJ_R_TX_INTERVAL		3U
#define ETC_CFG_OBJ_R_LOG_INTERVAL		4U
#define ETC_CFG_OBJ_R_LOG_INTERVAL_ALARM	5U
#define ETC_CFG_OBJ_R_TX_DELAY			6U
#define ETC_CFG_OBJ_R_WAKE_EARLY		7U
#define ETC_CFG_OBJ_R_RX_DURATION		8U
#define ETC_CFG_OBJ_R_TX_INTERVAL_ALARM		9U

#define ETC_CFG_OBJ_R_DEVICE_MODE_MIN_VAL		0U
#define ETC_CFG_OBJ_R_DEVICE_MODE_MAX_VAL		2U
#define ETC_CFG_OBJ_R_POWER_MODE_MIN_VAL		0U
#define ETC_CFG_OBJ_R_POWER_MODE_MAX_VAL		1U
#define ETC_CFG_OBJ_R_TX_INTERVAL_MIN_VAL		60U
#define ETC_CFG_OBJ_R_TX_INTERVAL_MAX_VAL		86400U
#define ETC_CFG_OBJ_R_LOG_INTERVAL_MIN_VAL		60U
#define ETC_CFG_OBJ_R_LOG_INTERVAL_MAX_VAL		86400U
#define ETC_CFG_OBJ_R_LOG_INTERVAL_ALARM_MIN_VAL	60U
#define ETC_CFG_OBJ_R_LOG_INTERVAL_ALARM_MAX_VAL	86400U
#define ETC_CFG_OBJ_R_TX_DELAY_MIN_VAL                  0U
#define ETC_CFG_OBJ_R_TX_DELAY_MAX_VAL                  29500U
#define ETC_CFG_OBJ_R_WAKE_EARLY_MIN_VAL		0U
#define ETC_CFG_OBJ_R_WAKE_EARLY_MAX_VAL		840U
#define ETC_CFG_OBJ_R_RX_DURATION_MIN_VAL		30U
#define ETC_CFG_OBJ_R_RX_DURATION_MAX_VAL		300U
#define ETC_CFG_OBJ_R_TX_INTERVAL_ALARM_MIN_VAL		60U
#define ETC_CFG_OBJ_R_TX_INTERVAL_ALARM_MAX_VAL		86400U

#endif /* CONFIGURATION_OBJECT_H__ */