#ifndef ETC_LOCATION_OBJ_48938_H_
#define ETC_LOCATION_OBJ_48938_H_

#define ETC_LOCATION_OBJ_ID	48938

#define ETC_LOCATION_OBJ_R_LATITUDE	1
#define ETC_LOCATION_OBJ_R_LONGITUDE	2
#define ETC_LOCATION_OBJ_R_REQUEST	3

#endif // ETC_LOCATION_OBJ_48938_H_