/*
 * Copyright (c) 2023 EXACT Technology
 */

#ifndef ETC_RECLAIM_OBJ_48934_H__
#define ETC_RECLAIM_OBJ_48934_H__

#define ETC_RECLAIM_OBJECT_ID 48934

/* Configuration object resource IDs */
#define ETC_RECLAIM_OBJ_R_START_TIME	1U
#define ETC_RECLAIM_OBJ_R_END_TIME  	2U
#define ETC_RECLAIM_OBJ_R_RECLAIM	3U
#define ETC_RECLAIM_OBJ_R_STATUS	4U
#define ETC_RECLAIM_OBJ_R_CANCEL	5U

#define ETC_RECLAIM_STATUS_IDLE		0U
#define ETC_RECLAIM_STATUS_IN_PROGRESS	1U
#define ETC_RECLAIM_STATUS_COMPLETE	2U
#define ETC_RECLAIM_STATUS_ERROR	3U
#define ETC_RECLAIM_STATUS_CANCELLED	4U
#define ETC_RECLAIM_STATUS_NO_RECORDS	5U

#endif /* ETC_RECLAIM_OBJ_48934_H__ */