#ifndef ETC_FUNCTIONAL_TEST_OBJ_48937_H__
#define ETC_FUNCTIONAL_TEST_OBJ_48937_H__

#define ETC_FUNCTIONAL_TEST_OBJECT_ID		48937

#define ETC_FUNCTIONAL_TEST_OBJ_R_STATUS	1

#endif // ETC_FUNCTIONAL_TEST_OBJ_48937_H__