#ifndef ETC_CALIBRATION_OBJ_48950_H_
#define ETC_CALIBRATION_OBJ_48950_H_

#define ETC_CALIBRATION_OBJ_ID 48950

#define ETC_CALIBRATION_R_TYPE	    1
#define ETC_CALIBRATION_R_TIME	    2
#define ETC_CALIBRATION_R_ID	    3
#define ETC_CALIBRATION_R_OFFSET    4
#define ETC_CALIBRATION_R_HIGH	    5
#define ETC_CALIBRATION_R_REFERENCE 6

#define ETC_CALIBRATOR_ID_NUMBER_SIZE 8

#endif // ETC_CALIBRATION_OBJ_48950_H_