/* 
 * Copyright (c) 2023 EXACT Technology
 */

#ifndef CONFIGURATION_OBJECT_H__
#define CONFIGURATION_OBJECT_H__

#define ETC_CFG_OBJECT_ID	48931

/* Configuration object resource IDs */
#define ETC_CFG_OBJ_R_DEVICE_MODE		1U
#define ETC_CFG_OBJ_R_POWER_MODE		2U
#define ETC_CFG_OBJ_R_TX_INTERVAL		3U
#define ETC_CFG_OBJ_R_LOG_INTERVAL		4U
#define ETC_CFG_OBJ_R_LOG_INTERVAL_ALARM	5U
#define ETC_CFG_OBJ_R_TX_DELAY			6U
#define ETC_CFG_OBJ_R_WAKE_EARLY		7U
#define ETC_CFG_OBJ_R_RX_DURATION		8U
#define ETC_CFG_OBJ_R_TX_INTERVAL_ALARM		9U
#define ETC_CFG_OBJ_R_TX_PROBE 			10U
#define ETC_CFG_OBJ_R_LORA_PROBE_OFFSET		11U
#define ETC_CFG_OBJ_R_LTE_PROBE_OFFSET		12U
#define ETC_CFG_OBJ_R_LOCATION_REQ_INTERVAL	13U
#define ETC_CFG_OBJ_R_GNSS_TIMEOUT		14U

#define ETC_CFG_OBJ_R_DEVICE_MODE_MIN_VAL		0U
#define ETC_CFG_OBJ_R_DEVICE_MODE_MAX_VAL		3U
#define ETC_CFG_OBJ_R_POWER_MODE_MIN_VAL		1U
#define ETC_CFG_OBJ_R_POWER_MODE_MAX_VAL		2U
#define ETC_CFG_OBJ_R_TX_INTERVAL_MIN_VAL		60U
#define ETC_CFG_OBJ_R_TX_INTERVAL_MAX_VAL		86400U
#define ETC_CFG_OBJ_R_LOG_INTERVAL_MIN_VAL		60U
#define ETC_CFG_OBJ_R_LOG_INTERVAL_MAX_VAL		86400U
#define ETC_CFG_OBJ_R_LOG_INTERVAL_ALARM_MIN_VAL	60U
#define ETC_CFG_OBJ_R_LOG_INTERVAL_ALARM_MAX_VAL	86400U
#define ETC_CFG_OBJ_R_TX_DELAY_MIN_VAL			0U
#define ETC_CFG_OBJ_R_TX_DELAY_MAX_VAL			29500U
#define ETC_CFG_OBJ_R_WAKE_EARLY_MIN_VAL		0U
#define ETC_CFG_OBJ_R_WAKE_EARLY_MAX_VAL		840U
#define ETC_CFG_OBJ_R_RX_DURATION_MIN_VAL		30U
#define ETC_CFG_OBJ_R_RX_DURATION_MAX_VAL		300U
#define ETC_CFG_OBJ_R_TX_INTERVAL_ALARM_MIN_VAL		60U
#define ETC_CFG_OBJ_R_TX_INTERVAL_ALARM_MAX_VAL		86400U
#define ETC_CFG_OBJ_R_TX_PROBE_MIN_VAL			21600U
#define ETC_CFG_OBJ_R_TX_PROBE_MAX_VAL			86400U	
#define ETC_CFG_OBJ_R_LORA_PROBE_OFFSET_MIN_VAL		0U
#define ETC_CFG_OBJ_R_LORA_PROBE_OFFSET_MAX_VAL		2700U	
#define ETC_CFG_OBJ_R_LTE_PROBE_OFFSET_MIN_VAL		0U
#define ETC_CFG_OBJ_R_LTE_PROBE_OFFSET_MAX_VAL		3540U
#define ETC_CFG_OBJ_R_LOCATION_REQ_INTERVAL_MIN_VAL	0U
#define ETC_CFG_OBJ_R_LOCATION_REQ_INTERVAL_MAX_VAL	(60LU * 60LU * 24LU * 7LU ) /* 7 days */
#define ETC_CFG_OBJ_R_GNSS_TIMEOUT_MIN_VAL		60U
#define ETC_CFG_OBJ_R_GNSS_TIMEOUT_MAX_VAL		600U

#endif /* CONFIGURATION_OBJECT_H__ */
