#ifndef ETC_CALIBRATION_OBJ_STATUS_48939_H_
#define ETC_CALIBRATION_OBJ_STATUS_48939_H_

#define ETC_CALIBRATION_STATUS_OBJ_ID 48939

#define ETC_CALIBRATION_STATUS_R_STATUS	      1
#define ETC_CALIBRATION_STATUS_R_RESULT	      2
#define ETC_CALIBRATION_STATUS_R_PRE_VALUES   3
#define ETC_CALIBRATION_STATUS_R_POST_VALUES  4
#define ETC_CALIBRATION_STATUS_R_REF_VALUES   5
#define ETC_CALIBRATION_STATUS_R_ACTIVE_CALIB 6

#define ETC_ADJUSTMENT_MAX_STR_SIZE 128
#define ETC_REFERENCE_MAX_STR_SIZE  32

#define ETC_CALIBRATION_STATUS_R_STATUS_MIN 0
#define ETC_CALIBRATION_STATUS_R_STATUS_MAX 5

#define ETC_CALIBRATION_STATUS_R_RESULT_MIN 0
#define ETC_CALIBRATION_STATUS_R_RESULT_MAX 255

#endif /* ETC_CALIBRATION_OBJ_STATUS_48939_H_ */