# General config
CONFIG_TEST_VERSION="v1.0.0"
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_ASSERT=y
CONFIG_REBOOT=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_FPU=y
CONFIG_FW_INFO=y
CONFIG_CJSON_LIB=y

# Disable boot banner. printk outputs get dropped w/ usbcdc
CONFIG_BOOT_BANNER=n
# Heap and stacks
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_LOG=y

# Heap and stacks
CONFIG_HW_STACK_PROTECTION=y

# Settings, needed for Azure Device Provisioning Service
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_SHELL=y
CONFIG_FCB=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

# Flash Settings
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_SOC_FLASH_NRF_UICR=y
CONFIG_FLASH_MAP=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_FLASH_JESD216_API=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y

# CJSON
CONFIG_CJSON_LIB=y

CONFIG_ADC=y
CONFIG_ADC_MODULES=y
CONFIG_PCF85263_WATCHDOG_FEED_INTERNAL_SECONDS=10
CONFIG_PCF85263=y
CONFIG_DS2484=y
CONFIG_DS18B20=y
CONFIG_DS18B20_TIMER=y

# GUI over LED
CONFIG_UI_MODULE=y
CONFIG_UI_LED_USE_PWM=y
CONFIG_UI_LOG_LEVEL_WRN=y

CONFIG_SHELL=y
CONFIG_SHELL_VT100_COLORS=n
CONFIG_SHELL_LOG_LEVEL_INF=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="ETC USB Shell"
CONFIG_SHELL_BACKEND_SERIAL_CHECK_DTR=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_BACKEND_SERIAL_INIT_PRIORITY=51
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=128

CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_LORA=y
CONFIG_LORA_SX127X=y
CONFIG_LORA_LOG_LEVEL_WRN=y

# Enable peripheral
CONFIG_SPI=y
CONFIG_SPI_NOR=y

CONFIG_ADC=y
CONFIG_PWM=y
CONFIG_I2C=y

CONFIG_SENSOR=y

# Enable mcumgr.
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y
CONFIG_CRC=y
CONFIG_MCUMGR=y

# Some command handlers require a large stack.
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2304
CONFIG_MAIN_STACK_SIZE=2048

# Enable flash operations.
CONFIG_FLASH=y

# Allow for large Bluetooth data packets.
CONFIG_BT_DEVICE_NAME="ETC-MCUMGR"
CONFIG_BT_L2CAP_TX_MTU=498
CONFIG_BT_BUF_ACL_RX_SIZE=502
CONFIG_BT_BUF_ACL_TX_SIZE=502
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251

# Enable the Bluetooth mcumgr transport (unauthenticated).
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_TRANSPORT_BT_AUTHEN=n
CONFIG_MCUMGR_TRANSPORT_BT_CONN_PARAM_CONTROL=y

# Enable the Shell mcumgr transport.
CONFIG_MCUMGR_GRP_SHELL=y
CONFIG_MCUMGR_GRP_OS=y

# Enable the mcumgr Packet Reassembly feature over Bluetooth and its configuration dependencies.
# MCUmgr buffer size is optimized to fit one SMP packet divided into five Bluetooth Write Commands,
# transmitted with the maximum possible MTU value: 498 bytes.
CONFIG_MCUMGR_TRANSPORT_BT_REASSEMBLY=y
CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=2475
CONFIG_MCUMGR_GRP_OS_MCUMGR_PARAMS=y
CONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=4608

# Disable Bluetooth ping support
CONFIG_BT_CTLR_LE_PING=n

# Disable shell commands that are not needed
CONFIG_CLOCK_CONTROL_NRF_SHELL=n
CONFIG_DEVICE_SHELL=n
CONFIG_DEVMEM_SHELL=n

# Enable Power Management module
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y

# Enable log debug
CONFIG_ETC_TEST_LOG_LEVEL_DBG=y
CONFIG_ETC_WATCHDOG_LOG_LEVEL_INF=y

# Enable Lora message when HALL trigger event
CONFIG_LORA_MSG_IN_HALL_EVENT=n

# Needed for RTC calibration
CONFIG_NRFX_TIMER1=y
CONFIG_NRFX_TIMER2=y
CONFIG_NRFX_EGU0=y

# Make sure etc_device is initialized before USB
CONFIG_ETC_DEVICE_INIT_PRIORITY=80
CONFIG_APPLICATION_INIT_PRIORITY=90