# General config
CONFIG_TEST_VERSION="v1.0.0"
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_ASSERT=y
CONFIG_REBOOT=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_FPU=y
CONFIG_FW_INFO=y
CONFIG_CJSON_LIB=y

# Heap and stacks
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_LOG=y

# Heap and stacks
CONFIG_HW_STACK_PROTECTION=y

# Settings, needed for Azure Device Provisioning Service
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FCB=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

# Flash Settings
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_SOC_FLASH_NRF_UICR=y
CONFIG_FLASH_MAP=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_STREAM_FLASH_LOG_LEVEL_DBG=y
CONFIG_FLASH_JESD216_API=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y

# CJSON
CONFIG_CJSON_LIB=y

CONFIG_ADC=y
CONFIG_ADC_MODULES_SAMPLE_RATE_MSEC=30000
CONFIG_ADC_MODULES=y
CONFIG_BQ24195=y
CONFIG_PCF85263=y
CONFIG_PCF85263_LOG_LEVEL_DBG=y
# CONFIG_DS2484=y
CONFIG_DS18B20=y

# GUI over LED
CONFIG_UI_MODULE=y
CONFIG_UI_LED_USE_PWM=y
CONFIG_UI_LOG_LEVEL_DBG=y
CONFIG_UI_LED_RED_PIN=34
CONFIG_UI_LED_GREEN_PIN=38
CONFIG_UI_LED_BLUE_PIN=25

CONFIG_SHELL=y
CONFIG_SHELL_LOG_LEVEL_INF=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="ETC USB Shell"
CONFIG_SHELL_BACKEND_SERIAL_CHECK_DTR=y
CONFIG_UART_LINE_CTRL=y
CONFIG_SHELL_BACKEND_SERIAL_INIT_PRIORITY=51

CONFIG_LORA=y
CONFIG_LORA_SX12XX=y