name: Build Application

on:
  push:
    branches:
      - main
      - v*
      - RC/*
      - dev
    tags:
      - v*
  pull_request:
    branches:
      - main
      - v*
      - RC/*
      - dev
    paths:
      - 'applications/etc-app/**'
      - 'boards/**'
      - 'lib/**'
      - 'drivers/**'
      - 'patch/**'
      - '.github/workflows/build_app.yml'
  workflow_dispatch:
    inputs:
      carrier:
        description: 'Carrier selection'
        required: false
        type: choice
        default: ''
        options:
          - ''
          - soracom
          - teal

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}-${{ inputs.carrier || 'default' }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [base, memfault]
        key: [dev, production]

    steps:
      - name: Free space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set carrier variables
        run: |
          carrier="${{ inputs.carrier }}"
          if [ "$carrier" = "soracom" ]; then
            echo "carrier_overlay=overlay-soracom.conf" >> "$GITHUB_ENV"
            echo "carrier_cmake=-DPROJECT_VERSION_CARRIER=sora" >> "$GITHUB_ENV"
            echo "carrier_prefix=soracom_" >> "$GITHUB_ENV"
            echo "carrier_file_prefix=soracom_" >> "$GITHUB_ENV"
          elif [ "$carrier" = "teal" ]; then
            echo "carrier_overlay=overlay-teal.conf" >> "$GITHUB_ENV"
            echo "carrier_cmake=-DPROJECT_VERSION_CARRIER=teal" >> "$GITHUB_ENV"
            echo "carrier_prefix=teal_" >> "$GITHUB_ENV"
            echo "carrier_file_prefix=teal_" >> "$GITHUB_ENV"
          else
            echo "carrier_overlay=" >> "$GITHUB_ENV"
            echo "carrier_cmake=" >> "$GITHUB_ENV"
            echo "carrier_prefix=" >> "$GITHUB_ENV"
            echo "carrier_file_prefix=" >> "$GITHUB_ENV"
          fi

      - name: Setup etc common SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ETC_COMMON_PRIV_SSH_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: etc-firmware

      - name: Configure Git
        working-directory: etc-firmware
        run: |
            git config --global user.email "actions@exacttechnology.com"
            git config --global user.name "Github Actions"

      - name: Set variables
        working-directory: etc-firmware
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Install python dependencies
        run: |
          pip3 install memfault-cli
          pip3 install imgtool==2.0.0

      - name: Cache West dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-west
        with:
          path: |
            ./zephyr
            ./tools
            ./test
            ./nrfxlib
            ./nrf
            ./modules
            ./mbedtls
            ./bootloader
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('etc-firmware/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: etc-firmware
          toolchains: arm-zephyr-eabi
          sdk-version: 0.16.8

      - name: Apply patches
        working-directory: etc-firmware
        run: |
          ./scripts/apply_patches.sh

      - name: Retrieve signing key and save to file
        working-directory: etc-firmware
        if: ${{ matrix.key == 'production' }}
        env:
          MCUBOOT_PRIVATE_KEY_BASE64: ${{ secrets.MCUBOOT_PRIVATE_KEY_BASE64 }}
        run: |
          echo $MCUBOOT_PRIVATE_KEY_BASE64 | base64 --decode > mcuboot.pem
          echo "mcuboot_key_path=$(realpath mcuboot.pem)" >> "$GITHUB_ENV"

      - name: Set mcuboot key path to default
        if: ${{ matrix.key == 'dev' }}
        run: |
          echo "mcuboot_key_path=root-rsa-2048.pem" >> "$GITHUB_ENV"

      - name: Memfault Overlay
        if: ${{ matrix.type == 'memfault' }}
        run: |
          if [ -n "$carrier_overlay" ]; then
            echo "overlays=-DEXTRA_CONF_FILE=debug.conf;rtt.conf;overlay-memfault.conf;${carrier_overlay}" >> "$GITHUB_ENV"
          else
            echo "overlays=-DEXTRA_CONF_FILE=debug.conf;rtt.conf;overlay-memfault.conf" >> "$GITHUB_ENV"
          fi

      - name: Base Overlay
        if: ${{ matrix.type == 'base' }}
        run: |
          if [ -n "$carrier_overlay" ]; then
            echo "overlays=-DEXTRA_CONF_FILE=${carrier_overlay}" >> "$GITHUB_ENV"
          else
            echo "overlays=" >> "$GITHUB_ENV"
          fi

      - name: Build etc-app ${{ matrix.type }}_${{ matrix.key }}
        working-directory: etc-firmware
        run: |
          west build -b etc_flex/nrf52840 -s applications/etc-app -d build_${{ matrix.type }}_${{ matrix.key }} -p -- \
            $overlays \
            $carrier_cmake \
            -Dmcuboot_CONFIG_BOOT_SIGNATURE_KEY_FILE=\"$mcuboot_key_path\"

      - name: Upload symbol file to Memfault
        working-directory: etc-firmware
        env:
          MEMFAULT_ORG_TOKEN: ${{ secrets.MEMFAULT_ORG_TOKEN }}
          MEMFAULT_ORG: ${{ vars.MEMFAULT_ORG }}
          MEMFAULT_PROJECT: ${{ vars.MEMFAULT_PROJECT }}
        if: ${{ matrix.type == 'memfault' }}
        run: |
          echo $MEMFAULT_ORG_TOKEN
          echo $MEMFAULT_ORG
          echo $MEMFAULT_PROJECT
          memfault \
            --org-token $MEMFAULT_ORG_TOKEN \
            --org $MEMFAULT_ORG \
            --project $MEMFAULT_PROJECT \
            upload-mcu-symbols build_${{ matrix.type }}_${{ matrix.key }}/zephyr/zephyr.elf

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_${{ env.carrier_prefix }}${{ matrix.type }}_${{ matrix.key }}
          path: |
            etc-firmware/build_${{ matrix.type }}_${{ matrix.key }}/zephyr/merged.hex
            etc-firmware/build_${{ matrix.type }}_${{ matrix.key }}/zephyr/app_update.bin
            etc-firmware/build_${{ matrix.type }}_${{ matrix.key }}/zephyr/app_signed.hex
            etc-firmware/build_${{ matrix.type }}_${{ matrix.key }}/zephyr/zephyr.elf
          retention-days: 1

  release_package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set carrier variables
        run: |
          carrier="${{ inputs.carrier }}"
          if [ "$carrier" = "soracom" ]; then
            echo "carrier_prefix=soracom_" >> "$GITHUB_ENV"
            echo "carrier_file_prefix=soracom_" >> "$GITHUB_ENV"
          elif [ "$carrier" = "teal" ]; then
            echo "carrier_prefix=teal_" >> "$GITHUB_ENV"
            echo "carrier_file_prefix=teal_" >> "$GITHUB_ENV"
          else
            echo "carrier_prefix=" >> "$GITHUB_ENV"
            echo "carrier_file_prefix=" >> "$GITHUB_ENV"
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: etc-firmware

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: etc-firmware/build_memfault_dev
          name: build_${{ env.carrier_prefix }}memfault_dev

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: etc-firmware/build_memfault_production
          name: build_${{ env.carrier_prefix }}memfault_production

      - name: Install python dependencies
        run: |
          pip3 install imgtool==2.0.0

      - name: Copy output files
        working-directory: etc-firmware
        run: |
          mkdir -p out/update
          mkdir -p out/misc
          commit_id=$(git rev-parse --short HEAD)
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            version=$(echo "${{ github.ref }}" | sed 's|refs/tags/||')
          elif [[ "${{ github.ref }}" == refs/heads/RC/* ]]; then
            version=$(echo "${{ github.ref }}" | sed 's|refs/heads/RC/||')
          elif [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            commit_id=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c 1-8)
            pr_branch=$(echo "${{ github.head_ref }}" | sed 's:.*/::')
            version="${pr_branch}_${commit_id}"
          else
            head_branch=$(echo "${{ github.ref }}" | sed 's:.*/::')
            version="${head_branch}_${commit_id}"
          fi
          for type in memfault; do
            for key in dev production; do
              build_dir=build_${type}_${key}
              pubkey_id=$(python scripts/imgtools/etc_imgtool.py pubkeyid $build_dir/app_update.bin)
              cp $build_dir/merged.hex "out/flex_${carrier_file_prefix}${version}_pubkey-${pubkey_id}.hex"
              cp $build_dir/app_update.bin "out/update/update_flex_${carrier_file_prefix}${version}_pubkey-${pubkey_id}.bin"
              cp $build_dir/app_signed.hex "out/misc/update_test_flex_${carrier_file_prefix}${version}_pubkey-${pubkey_id}.hex"
              cp $build_dir/zephyr.elf "out/misc/flex_${carrier_file_prefix}${version}_pubkey-${pubkey_id}.elf"
            done
          done
          echo "APP_VERSION=${version}" >> $GITHUB_ENV


      - name: Upload output files
        uses: actions/upload-artifact@v4
        with:
          name: flex_${{ env.carrier_file_prefix }}${{ env.APP_VERSION }}
          path: etc-firmware/out/
