name: Build Application

on:
  push:
    branches: 
      - main
      - v*
      - RC/*
      - dev
    tags:
      - v*
  pull_request:
    branches:
      - main
      - v*
      - RC/*
      - dev
    paths:
      - 'applications/etc-app/**'
      - 'boards/**'
      - 'lib/**'
      - 'drivers/**'
      - 'patch/**'
      - '.github/workflows/build_app.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [base, memfault]
        key: [dev, production]

    steps:
      - name: Free space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: etc-firmware

      - name: Configure Git
        working-directory: etc-firmware
        run: |
            git config --global user.email "actions@exacttechnology.com"
            git config --global user.name "Github Actions"

      - name: Set variables
        working-directory: etc-firmware
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
     
      - name: Install python dependencies
        run: |
          pip3 install memfault-cli
          pip3 install imgtool==2.0.0

      - name: Cache West dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-west
        with:
          path: |
            ./zephyr
            ./tools
            ./test
            ./nrfxlib
            ./nrf
            ./modules
            ./mbedtls
            ./bootloader
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('etc-firmware/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      
      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: etc-firmware
          toolchains: arm-zephyr-eabi
          sdk-version: 0.16.5-1
      
      - name: Apply patches
        working-directory: etc-firmware
        run: |
          ./scripts/apply_patches.sh

      - name: Retrieve signing key and save to file
        working-directory: etc-firmware
        if: ${{ matrix.key == 'production' }}
        env:
          MCUBOOT_PRIVATE_KEY_BASE64: ${{ secrets.MCUBOOT_PRIVATE_KEY_BASE64 }}
        run: |
          echo $MCUBOOT_PRIVATE_KEY_BASE64 | base64 --decode > mcuboot.pem
          echo "mcuboot_key_path=$(realpath mcuboot.pem)" >> "$GITHUB_ENV"

      - name: Set mcuboot key path to default
        if: ${{ matrix.key == 'dev' }}
        run: |
          echo "mcuboot_key_path=root-rsa-2048.pem" >> "$GITHUB_ENV"

      - name: Memfault Overlay
        if: ${{ matrix.type == 'memfault' }}
        run: |
          echo "overlays=-DOVERLAY_CONFIG=debug.conf;rtt.conf;overlay-memfault.conf;overlay-1nce.conf" >> "$GITHUB_ENV"

      - name: Base Overlay
        if: ${{ matrix.type == 'base' }}
        run: |
          echo "overlays=" >> "$GITHUB_ENV"
          
      - name: Build etc-app ${{ matrix.sample }}
        working-directory: etc-firmware
        run: |
          west build -b etc@0.3.0 -s applications/etc-app -p -- \
            $overlays \
            -Dmcuboot_CONFIG_BOOT_SIGNATURE_KEY_FILE=\"$mcuboot_key_path\"

      - name: Upload symbol file to Memfault
        working-directory: etc-firmware
        env:
          MEMFAULT_ORG_TOKEN: ${{ secrets.MEMFAULT_ORG_TOKEN }}
          MEMFAULT_ORG: ${{ vars.MEMFAULT_ORG }}
          MEMFAULT_PROJECT: ${{ vars.MEMFAULT_PROJECT }}
        if: ${{ matrix.type == 'memfault' }}
        run: |
          echo $MEMFAULT_ORG_TOKEN
          echo $MEMFAULT_ORG
          echo $MEMFAULT_PROJECT
          memfault \
            --org-token $MEMFAULT_ORG_TOKEN \
            --org $MEMFAULT_ORG \
            --project $MEMFAULT_PROJECT \
            upload-mcu-symbols build/zephyr/zephyr.elf

      - name: Extract pubkey ID
        working-directory: etc-firmware
        run: |
          echo "pubkey_id=$(python scripts/imgtools/etc_imgtool.py pubkeyid build/zephyr/app_update.bin)" \
            >> "$GITHUB_ENV"

      - name: Copy output files
        working-directory: etc-firmware
        run: |
          mkdir -p out/update
          cp build/zephyr/merged.hex out/flex_${{ matrix.type }}_${sha_short}_pubkey-${pubkey_id}.hex
          cp build/zephyr/app_update.bin "out/update/update_flex_${{ matrix.type }}_${sha_short}_pubkey-${pubkey_id}.bin"
          mkdir out/misc
          cp build/zephyr/app_signed.hex "out/misc/update_test_flex_${{ matrix.type }}_${sha_short}_pubkey-${pubkey_id}.hex"
          cp build/zephyr/zephyr.elf "out/misc/flex_${{ matrix.type }}_${sha_short}_pubkey-${pubkey_id}.elf"

      - name: Upload output files
        uses: actions/upload-artifact@v4
        with:
          name: flex_${{ env.sha_short }}_${{ matrix.type }}_${{ env.pubkey_id }}
          path: etc-firmware/out/