name: Build etc-test

on:
  push:
    branches: 
      - main
      - v*
      - RC/*
      - dev
    tags:
      - v*
  pull_request:
    branches:
      - main
      - v*
      - RC/*
      - dev
    paths:
      - 'applications/etc-test/**'
      - 'boards/**'
      - 'lib/**'
      - '.github/workflows/build_test.yml'


concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Setup etc common SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ETC_COMMON_PRIV_SSH_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: etc-firmware
      
      - name: Configure Git
        working-directory: etc-firmware
        run: |
            git config --global user.email "actions@exacttechnology.com"
            git config --global user.name "Github Actions"

      - name: Set variables
        working-directory: etc-firmware
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Cache West dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-west
        with:
          path: |
            ./zephyr
            ./tools
            ./test
            ./nrfxlib
            ./nrf
            ./modules
            ./mbedtls
            ./bootloader
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('etc-firmware/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: etc-firmware
          toolchains: arm-zephyr-eabi
          sdk-version: 0.16.8

      - name: Apply patches
        working-directory: etc-firmware
        run: |
          ./scripts/apply_patches.sh

      - name: Build etc-test
        working-directory: etc-firmware
        run: |
          west build -b etc_flex/nrf52840 -s applications/etc-test -p
          mkdir out
          cp build/zephyr/merged.hex out/etc_test_${sha_short}.hex
      
      - name: Upload output files
        uses: actions/upload-artifact@v4
        with:
          name: etc_test_${{ env.sha_short }}
          path: etc-firmware/out/