name: Run tests with twister

on:
  push:
    branches:
      - dev
      - v*
      - RC/v*
  pull_request:
    branches:
      - dev
      - v*
      - RC/v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Free space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: etc-firmware
          fetch-depth: 0

      - name: Configure Git
        working-directory: etc-firmware
        run: |
            git config --global user.email "actions@exacttechnology.com"
            git config --global user.name "Github Actions"

      - name: Cache West dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-west
        with:
          path: |
            ./zephyr
            ./tools
            ./test
            ./nrfxlib
            ./nrf
            ./modules
            ./mbedtls
            ./bootloader
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('etc-firmware/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: etc-firmware
          toolchains: arm-zephyr-eabi
          sdk-version: 0.16.5-1

      - name: Run all tests in the etc-firmware project
        run: |
            ./zephyr/scripts/twister -T ./etc-firmware/tests

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results
          path: |
            twister-out/twister.xml
            twister-out/twister_report.xml
            twister-out/twister.json