add_subdirectory_ifdef(CONFIG_ETC_DATE_TIME etc_date_time)
add_subdirectory_ifdef(CONFIG_ETC_INTERFACE etc_interface)
add_subdirectory_ifdef(CONFIG_ETC_SETTINGS etc_settings)
add_subdirectory_ifdef(CONFIG_WATCHDOG_APPLICATION watchdog)
add_subdirectory_ifdef(CONFIG_MCUMGR_CMD_ETC_MGMT etc_mgmt)
add_subdirectory(etc_devices)
add_subdirectory(etc_util)